version: '3'
services:

  app:
    image: welinju/pythonflask:latest
    container_name: app
    volumes:
      - ./:/code
    ports:
      - "80:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge